config/routes.rb
Rails.application.routes.draw do

  get 'contact-me', to: 'messages#new', as: 'new_message'
  post 'contact-me', to: 'messages#create', as: 'create_message'

  get 'estimate', to: 'estimates#new', as: 'new_estimates'
  post 'estimate', to: 'estimates#create', as: 'create_estimates'
  
  get 'request', to: 'request#new', as: 'new_request'
  post 'request', to: 'request#create', as: 'create_request'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/estimate.rb
class Estimate
    include ActiveModel::Model
    attr_accessor :first_name, 
                :last_name, 
                :email, 
                :phone, 
                :contact_time, 
                :house_number, 
                :street_name, 
                :address_two, 
                :city, 
                :state,
                :zip_code,
                :square_feet,
                :bedrooms, 
                :bathrooms,
                :year_built,
                :property_type,
                :features,
                :comments

    validates   :first_name, 
                :last_name, 
                :email, 
                :phone, 
                :contact_time, 
                :house_number, 
                :street_name,
                :city, 
                :state, 
                :square_feet,
                :bedrooms, 
                :bathrooms,
                :year_built,
                :property_type,
                :features,
                :comments,
                presence: true
    validates   :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
    validates   :phone, phone: true   
    validates   :zip_code,
                :square_feet,
                :bedrooms, 
                :bathrooms,
                :year_built,
                numericality: true



end

app/models/message.rb
class Message
    include ActiveModel::Model
    attr_accessor :name, :email, :body

    validates :name, :email, :body, presence: true
end

app/models/request.rb
class Request
    include ActiveModel::Model
    attr_accessor :name,
                  :email,
                  :phone,
                  :address, 
                  :city,
                  :state,
                  :zip_code,
                  :music_choice,
                  :shipping_type,
                  :message

    validates   :name,
                :email,
                :phone,
                :address, 
                :city,
                :state,
                :zip_code,
                :music_choice,
                :shipping_type,
                :message,
                presence: true
    validates   :phone, phone: true
    validates   :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
    validates   :zip_code,
                numericality: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/estimates_controller.rb
class EstimatesController < ApplicationController
    
    def new
        @estimate = Estimate.new
    end

    def create
        @estimate = Estimate.new estimate_params

        if @estimate.valid?
            EstimateMailer.estimate_new(@estimate).deliver_now
            redirect_to new_estimates_url, notice: "Your estimate request has been submitted"
        else
            render :new
        end
    end

private 

    def estimate_params
        params.require(:estimate).permit(:first_name, 
                                        :last_name, 
                                        :email, 
                                        :phone, 
                                        :contact_time, 
                                        :house_number, 
                                        :street_name, 
                                        :address_two, 
                                        :city, 
                                        :state,
                                        :zip_code,
                                        :square_feet,
                                        :bedrooms, 
                                        :bathrooms,
                                        :year_built,
                                        :property_type,
                                        :features,
                                        :comments
                                        )
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    
    def new
        @message = Message.new
    end

    def create 
        @message = Message.new message_params

        if @message.valid?
            MessageMailer.contact_me(@message).deliver_now
            redirect_to new_message_url, notice: "Message received, thank you!"
        else
            render :new
        end
    end

private

    def message_params
        params.require(:message).permit(:name, :email, :body)
    end

end

app/controllers/request_controller.rb
class RequestController < ApplicationController

    def new
        @request = Request.new
    end

    def create
        @request = Request.new request_params
        
        if @request.valid?
            RequestMailer.request_new(@request).deliver_now
            redirect_to new_request_url, notice: "You have successfully submitted your request"
        else
            render :new
        end
    end

    private

    def request_params
        params.require(:request).permit(:name,
                                        :email,
                                        :phone,
                                        :address, 
                                        :city,
                                        :state,
                                        :zip_code,
                                        :music_choice,
                                        :shipping_type,
                                        :message
                                        )
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/estimates/new.html.erb
<%= form_for @estimate, url: create_estimates_url do |f| %>
    <%= notice %>
  <%= @estimate.errors.full_messages.join(', ') %>
  <%= f.text_field :first_name, placeholder: "First Name" %>
  <%= f.text_field :last_name, placeholder: "Last Name" %>
  <%= f.text_field :email, placeholder: "Email" %>
  <%= f.text_field :phone, placeholder: "Phone Number" %>
  <%= f.text_field :contact_time, placeholder: "Best time to contact" %>
  <%= f.text_field :house_number, placeholder: "House Number" %>
  <%= f.text_field :street_name, placeholder: "Street Name" %>
  <%= f.text_field :address_two, placeholder: "Address Line 2" %>
  <%= f.text_field :city, placeholder: "City" %>
  <%= f.text_field :state, placeholder: "State" %>
  <%= f.number_field :zip_code, placeholder: "Zip Code" %>
  <%= f.number_field :square_feet, placeholder: "Sqaure Feet" %>
  <%= f.number_field :bedrooms, placeholder:  "Number of Bedrooms" %>
  <%= f.number_field :bathrooms, placeholder: "Number of Bathrooms" %>
  <%= f.number_field :year_built, placeholder: "Year Built" %>
  <%= f.text_field :property_type, placeholder: "Property Type" %>
  <%= f.text_field :features, placeholder: "Features" %>
  <%= f.text_field :comments, placeholder: "Additional Comments" %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Template</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/new.html.erb
<%= form_for @message, url: create_message_url do |f| %>
  <%= notice %>
  <%= @message.errors.full_messages.join(', ') %>

  <%= f.text_field :name, placeholder: 'Name' %>
  <%= f.email_field :email, placeholder: 'Email' %>
  <%= f.text_area :body, placeholder: 'Body' %>
  <%= f.submit 'Send' %>
<% end %>

app/views/request/new.html.erb
<%= form_for @request, url: create_request_url do |f| %>
  <%= notice %>
  <%= @request.errors.full_messages.join(', ') %>

  <%= f.text_field :name, placeholder: 'Name' %>
  <%= f.email_field :email, placeholder: 'Email' %>
  <%= f.text_field :phone, placeholder: 'Phone Number' %>
  <%= f.text_field :address, placeholder: 'Address' %>
  <%= f.text_field :city, placeholder: 'City' %>
  <%= f.text_field :state, placeholder: 'State' %>
  <%= f.text_field :zip_code, placeholder: 'Zip Code' %>
  <%= f.text_field :music_choice, placeholder: 'Music Choice' %>
  <%= f.text_field :shipping_type, placeholder: 'Shipping Type' %>
  <%= f.text_area :message, placeholder: 'Message' %>
  <%= f.submit 'Send' %>
<% end %>